import React from "react";
import { Container, Col, Row } from "react-bootstrap";

function Brands() {
  return (
    <Container>
      <Row className="mt-2 mb-4">
        <Col md={12} className="overflow-auto">
          <table className="brand-table">
            <tr>
              <td>
                <img
                  src="https://res.cloudinary.com/dyff453oq/image/upload/v1679475034/ulux/brand-1_wnvfkp.png"
                  alt="brand"
                  className="brandImage"
                />
                <p>aaaaaa</p>
              </td>
              <td>
                <img
                  src="https://res.cloudinary.com/dyff453oq/image/upload/v1679475034/ulux/brand-1_wnvfkp.png"
                  alt="brand"
                  className="brandImage"
                />
                <p>aaaaaa</p>
              </td>
              <td>
                <img
                  src="https://res.cloudinary.com/dyff453oq/image/upload/v1679475034/ulux/brand-1_wnvfkp.png"
                  alt="brand"
                  className="brandImage"
                />
                <p>aaaaaa</p>
              </td>
              <td>
                <img
                  src="https://res.cloudinary.com/dyff453oq/image/upload/v1679475034/ulux/brand-1_wnvfkp.png"
                  alt="brand"
                  className="brandImage"
                />
                <p>aaaaaa</p>
              </td>
              <td>
                <img
                  src="https://res.cloudinary.com/dyff453oq/image/upload/v1679475034/ulux/brand-1_wnvfkp.png"
                  alt="brand"
                  className="brandImage"
                />
                <p>aaaaaa</p>
              </td>
              <td>
                <img
                  src="https://res.cloudinary.com/dyff453oq/image/upload/v1679475034/ulux/brand-1_wnvfkp.png"
                  alt="brand"
                  className="brandImage"
                />
                <p>aaaaaa</p>
              </td>
              <td>
                <img
                  src="https://res.cloudinary.com/dyff453oq/image/upload/v1679475034/ulux/brand-1_wnvfkp.png"
                  alt="brand"
                  className="brandImage"
                />
                <p>aaaaaa</p>
              </td>
              <td>
                <img
                  src="https://res.cloudinary.com/dyff453oq/image/upload/v1679475034/ulux/brand-1_wnvfkp.png"
                  alt="brand"
                  className="brandImage"
                />
                <p>aaaaaa</p>
              </td>
            </tr>
            <tr>
              <td>
                <img
                  src="https://res.cloudinary.com/dyff453oq/image/upload/v1679475034/ulux/brand-1_wnvfkp.png"
                  alt="brand"
                  className="brandImage"
                />
                <p>aaaaaa</p>
              </td>
              <td>
                <img
                  src="https://res.cloudinary.com/dyff453oq/image/upload/v1679475034/ulux/brand-1_wnvfkp.png"
                  alt="brand"
                  className="brandImage"
                />
                <p>aaaaaa</p>
              </td>
              <td>
                <img
                  src="https://res.cloudinary.com/dyff453oq/image/upload/v1679475034/ulux/brand-1_wnvfkp.png"
                  alt="brand"
                  className="brandImage"
                />
                <p>aaaaaa</p>
              </td>
              <td>
                <img
                  src="https://res.cloudinary.com/dyff453oq/image/upload/v1679475034/ulux/brand-1_wnvfkp.png"
                  alt="brand"
                  className="brandImage"
                />
                <p>aaaaaa</p>
              </td>
              <td>
                <img
                  src="https://res.cloudinary.com/dyff453oq/image/upload/v1679475034/ulux/brand-1_wnvfkp.png"
                  alt="brand"
                  className="brandImage"
                />
                <p>aaaaaa</p>
              </td>
              <td>
                <img
                  src="https://res.cloudinary.com/dyff453oq/image/upload/v1679475034/ulux/brand-1_wnvfkp.png"
                  alt="brand"
                  className="brandImage"
                />
                <p>aaaaaa</p>
              </td>
              <td>
                <img
                  src="https://res.cloudinary.com/dyff453oq/image/upload/v1679475034/ulux/brand-1_wnvfkp.png"
                  alt="brand"
                  className="brandImage"
                />
                <p>aaaaaa</p>
              </td>
              <td>
                <img
                  src="https://res.cloudinary.com/dyff453oq/image/upload/v1679475034/ulux/brand-1_wnvfkp.png"
                  alt="brand"
                  className="brandImage"
                />
                <p>aaaaaa</p>
              </td>
            </tr>
          </table>
        </Col>
      </Row>
    </Container>
  );
}

export default Brands;
